### ISSUE TITLE
Not Working

### ISSUE THREAD

**Issue by ogimenezb** [RuiVarela/Nespresso#1]
I'm testing, but I'm not able to DumpCard or DumpMoney. Dump is all blank. Line 365 is always blank.
Any ideas?

**Comment by RuiVarela** [comment]
Hello @ogimenezb , 
this  was a experimental project for which there will be no support, 
it served as a platform to learn mifare weaknesses
- it used a **mfoc** dump file or log, as input for mifare keys

**Comment by ogimenezb** [comment]
ok, thanks
